# pragma once
# include <ESP_Music.h>

/*
  Big Dick Randy - Custom Meme Beat (Inspired by DigBar style)
  generated by grok :sob:
*/

const int bpm = 80;

Note melody[] = {
// Big Dick Randy style piano riff (main motif)

{NOTE_GS4, N16}, {NOTE_GS4, N16}, {NOTE_GS4, N16}, {NOTE_REST, N16},
{NOTE_G4,  N16}, {NOTE_G4,  N16}, {NOTE_G4,  N16}, {NOTE_REST, N16},

{NOTE_F4,  N16}, {NOTE_F4,  N16}, {NOTE_F4,  N16}, {NOTE_REST, N16},
{NOTE_E4,  N16}, {NOTE_E4,  N16}, {NOTE_E4,  N16}, {NOTE_REST, N16},

// Repeat / variation
// {NOTE_GS4, N16}, {NOTE_GS4, N16}, {NOTE_GS4, N16}, {NOTE_REST, N16},
// {NOTE_G4,  N16}, {NOTE_G4,  N16}, {NOTE_G4,  N16}, {NOTE_REST, N16},

// {NOTE_F4,  N16}, {NOTE_F4,  N16}, {NOTE_F4,  N16}, {NOTE_REST, N16},
// {NOTE_E4,  N8},  {NOTE_REST, N8}, {NOTE_E4, N8}, {NOTE_REST, N8},
};

const int melodyLength = sizeof(melody) / sizeof(Note);